// Shared inline styles for the FinCopilot SPA (a small app — no CSS framework).
export const S = {
  center: { minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: '#0f172a', fontFamily: 'system-ui, sans-serif' },
  card: { width: 360, padding: 32, background: '#1e293b', borderRadius: 12, color: '#e2e8f0', boxShadow: '0 10px 40px rgba(0,0,0,0.4)' },
  brand: { margin: '0 0 4px', fontSize: 28, color: '#38bdf8' },
  tagline: { margin: '0 0 20px', color: '#94a3b8', fontSize: 14 },
  input: { width: '100%', boxSizing: 'border-box', padding: '10px 12px', marginBottom: 12, borderRadius: 8, border: '1px solid #334155', background: '#0f172a', color: '#e2e8f0', fontSize: 14 },
  row: { display: 'flex', gap: 8 },
  primary: { flex: 1, padding: '10px 12px', borderRadius: 8, border: 'none', background: '#38bdf8', color: '#0f172a', fontWeight: 600, cursor: 'pointer' },
  secondary: { flex: 1, padding: '10px 12px', borderRadius: 8, border: '1px solid #334155', background: 'transparent', color: '#e2e8f0', cursor: 'pointer' },
  error: { color: '#f87171', fontSize: 13, marginBottom: 12 },
  disclaimer: { marginTop: 16, fontSize: 11, color: '#64748b' },
  app: { display: 'flex', flexDirection: 'column', height: '100vh', background: '#0f172a', color: '#e2e8f0', fontFamily: 'system-ui, sans-serif' },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '12px 20px', borderBottom: '1px solid #1e293b' },
  brandSmall: { color: '#38bdf8', fontWeight: 700 },
  nav: { display: 'flex', gap: 6, flexWrap: 'wrap' },
  navBtn: { padding: '6px 14px', borderRadius: 8, border: '1px solid #334155', background: 'transparent', color: '#94a3b8', cursor: 'pointer', fontSize: 13 },
  navBtnActive: { padding: '6px 14px', borderRadius: 8, border: '1px solid #38bdf8', background: '#0b3a52', color: '#e2e8f0', cursor: 'pointer', fontSize: 13 },
  link: { background: 'none', border: 'none', color: '#94a3b8', cursor: 'pointer', fontSize: 13 },
  content: { flex: 1, overflowY: 'auto', padding: 20 },
  messages: { flex: 1, overflowY: 'auto', padding: 20, display: 'flex', flexDirection: 'column', gap: 12 },
  hint: { color: '#64748b', textAlign: 'center', marginTop: 40 },
  user: { alignSelf: 'flex-end', maxWidth: '75%', padding: '10px 14px', borderRadius: 12, background: '#38bdf8', color: '#0f172a' },
  assistant: { alignSelf: 'flex-start', maxWidth: '75%', padding: '10px 14px', borderRadius: 12, background: '#1e293b', whiteSpace: 'pre-wrap' },
  tools: { fontSize: 11, color: '#94a3b8', marginBottom: 4 },
  errText: { color: '#f87171' },
  composer: { display: 'flex', gap: 8, padding: 16, borderTop: '1px solid #1e293b' },
  composerInput: { flex: 1, padding: '10px 14px', borderRadius: 8, border: '1px solid #334155', background: '#1e293b', color: '#e2e8f0', fontSize: 14 },
  grid: { display: 'flex', gap: 12, flexWrap: 'wrap', marginBottom: 8 },
  statCard: { flex: '1 1 140px', background: '#1e293b', borderRadius: 10, padding: 16 },
  statLabel: { fontSize: 12, color: '#94a3b8' },
  statValue: { fontSize: 22, fontWeight: 700, marginTop: 4 },
  sectionTitle: { marginTop: 24, marginBottom: 10, fontSize: 15, color: '#cbd5e1' },
  chartRow: { display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 },
  barLabel: { width: 120, fontSize: 12, color: '#94a3b8', textAlign: 'right', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  bar: { height: 16, borderRadius: 4, minWidth: 2 },
  barValue: { fontSize: 12, color: '#cbd5e1', width: 90 },
  formRow: { display: 'flex', gap: 8, flexWrap: 'wrap', alignItems: 'center', marginBottom: 10 },
  small: { padding: '8px 10px', borderRadius: 8, border: '1px solid #334155', background: '#0f172a', color: '#e2e8f0', fontSize: 13 },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: 13, marginTop: 8 },
  th: { textAlign: 'left', color: '#94a3b8', borderBottom: '1px solid #334155', padding: '6px 8px' },
  td: { borderBottom: '1px solid #1e293b', padding: '6px 8px' },
  msg: { color: '#34d399', fontSize: 13, marginBottom: 10 },
  chatBar: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '8px 20px', borderBottom: '1px solid #1e293b' },
  hintSmall: { fontSize: 12, color: '#64748b' },
  sessionRow: { display: 'flex', alignItems: 'center', gap: 8, padding: '4px 6px 4px 14px', borderRadius: 10, border: '1px solid #334155', background: '#1e293b', color: '#e2e8f0' },
  sessionOpen: { flex: 1, display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 12, padding: '8px 6px', background: 'none', border: 'none', color: 'inherit', cursor: 'pointer', textAlign: 'left', font: 'inherit' },
  deleteBtn: { background: 'none', border: 'none', color: '#94a3b8', cursor: 'pointer', fontSize: 16, padding: '6px 10px', borderRadius: 6 },
  approvalCard: { display: 'flex', flexDirection: 'column', gap: 10, margin: '0 16px 8px', padding: 14, borderRadius: 10, border: '1px solid #f59e0b', background: '#3b2f1a', color: '#fde68a' },
  code: { fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace', background: '#0f172a', padding: '1px 5px', borderRadius: 4, fontSize: 13 },
  dataCard: { alignSelf: 'flex-start', maxWidth: '85%', padding: '10px 14px', borderRadius: 12, background: '#0b3a52', border: '1px solid #334155' },
  dataTitle: { fontSize: 12, color: '#94a3b8', marginBottom: 8 },
  markdown: { whiteSpace: 'normal', lineHeight: 1.45 },
  mdHeading: { fontSize: 15, margin: '6px 0 4px', color: '#cbd5e1' },
  mdPre: { background: '#0f172a', padding: 10, borderRadius: 8, overflowX: 'auto', margin: '6px 0' },
};
